#!/bin/bash

for i in {1..25}
do
	container=vm$i

	if [ "$1" == "destroy" ]
	then
		echo "Stopping $container"
		lxc-stop -n $container
		
		echo "Destroying $container"
		lxc-destroy -n $container
	else
		echo "Creating $container"
		lxc-create -n $container -t natty -f mylxc.conf
		rootfs=/var/lib/lxc/$container/rootfs

    		cat <<EOF > $rootfs/etc/rc.local
#!/bin/sh -x
sleep 5
apt-get update
ifconfig eth0
EOF
		lxc-start --define lxc.console=/var/log/lxc/$container -d -n $container
	fi
done
